// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4-ryPy_547F6NaKU-KheWk1xQxDBW-Tw',
    appId: '1:377859968173:web:159e00304668308b3a0a24',
    messagingSenderId: '377859968173',
    projectId: 'ipr-s3-app',
    authDomain: 'ipr-s3-app.firebaseapp.com',
    storageBucket: 'ipr-s3-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCabKuxl_3wNTbsxikhP9GsU7kBEm4pTIM',
    appId: '1:377859968173:android:d04bdf0e32912f2e3a0a24',
    messagingSenderId: '377859968173',
    projectId: 'ipr-s3-app',
    storageBucket: 'ipr-s3-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUs8W8sVK5x_s5VUg5HA455O7IM2dNScY',
    appId: '1:377859968173:ios:3eb754a8eb9810423a0a24',
    messagingSenderId: '377859968173',
    projectId: 'ipr-s3-app',
    storageBucket: 'ipr-s3-app.firebasestorage.app',
    iosBundleId: 'com.example.iprS3',
    iosClientId: '377859968173-6u55l5p6hpoe4lvkkjudjmmn4c72e01k.apps.googleusercontent.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUs8W8sVK5x_s5VUg5HA455O7IM2dNScY',
    appId: '1:377859968173:ios:3eb754a8eb9810423a0a24',
    messagingSenderId: '377859968173',
    projectId: 'ipr-s3-app',
    storageBucket: 'ipr-s3-app.firebasestorage.app',
    iosBundleId: 'com.example.iprS3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4-ryPy_547F6NaKU-KheWk1xQxDBW-Tw',
    appId: '1:377859968173:web:a91761b81321c94a3a0a24',
    messagingSenderId: '377859968173',
    projectId: 'ipr-s3-app',
    authDomain: 'ipr-s3-app.firebaseapp.com',
    storageBucket: 'ipr-s3-app.firebasestorage.app',
  );
}
